# https://hub.docker.com/_/influxdb
version: '3.8'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influx-data:/var/lib/influxdb2
    environment:
      # only needed for the first run
      #DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: my-user
      DOCKER_INFLUXDB_INIT_PASSWORD: my-password
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-token
# https://hub.docker.com/r/grafana/grafana/#!
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 6868:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
volumes:
  grafana-data: {}
  influx-data: {}
