# docker run -d -p 8086:8086 \
#       -v $PWD/data:/var/lib/influxdb2 \
#       -v $PWD/config:/etc/influxdb2 \
#       -e DOCKER_INFLUXDB_INIT_MODE=setup \
#       -e DOCKER_INFLUXDB_INIT_USERNAME=my-user \
#       -e DOCKER_INFLUXDB_INIT_PASSWORD=my-password \
#       -e DOCKER_INFLUXDB_INIT_ORG=my-org \
#       -e DOCKER_INFLUXDB_INIT_BUCKET=my-bucket \
#       influxdb:2.0

# docker-compose.yml
version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./influx_data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: my-user
      DOCKER_INFLUXDB_INIT_PASSWORD: my-password
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-token
